name: GitHub Actions Java test workflow # Workflow name
run-name: Running tests on github actions
on: [push] # Trigger the workflow on push events
jobs:
  java-test: # Job name
    runs-on: ubuntu-latest # Configures the job to run on the latest version of an Ubuntu Linux runner.
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup java # Install Java on the runner
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21"

      - name: Run tests
        run: mvn test

  another-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        run: ls -la
